[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_flags =
    -I include
    -I src
    -I lib
    -I lib/drivers
    -I lib/Util
    -DARDUINO_MAIN_DEFINED
    -I .pio/build/megaatmega2560/unity_config
    -DUNITY_INCLUDE_CONFIG_H

test_framework = unity
test_build_src = no
lib_deps =
    throwtheswitch/Unity @ ^2.6.1

build_src_filter = +<*>