[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_flags =
    -I include
    -I src
    -I lib
    -DARDUINO_MAIN_DEFINED

[env:native]
platform = native
build_flags =
    -I lib/Util
    -I lib/drivers
test_filter = test_ringbuffer
